import crypto from "crypto";

// Based on a version generated by ChatGPT
export function generateIdFromNumber(num: number) {
  const luckyChars = ["K", "C", "D", "U"];
  const first = luckyChars[Math.abs(num) % luckyChars.length];

  const hash = crypto.createHash("sha256").update(num.toString()).digest();

  return first + compressHash(hash);
}

// Created by ChatGPT
function compressHash(hash: Buffer) {
  let num = parseInt(hash.toString("hex"), 16);
  const base = 62;
  const alphabet =
    "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
  let result = "";
  while (result.length < 5) {
    const remainder = num % base;
    result += alphabet.charAt(remainder);
    num = Math.floor(num / base);
  }

  return result;
}
